# title: Christine Ye
#  Christine Ye's personal website :)
url: "https://christine8888.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: christinexye
# github_username: christine8888

plugins:
  - jekyll-feed

theme: minima

permalink: /:title.html
source: .
destination: _site

collections_dir: _all_posts
collections:
  published:
    output: true
    permalink: /:title.html
  private:
    output: true
    permalink: /:title.html
  drafts:
    output: false
    

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/